### ISSUE TITLE
SGD_eval_script.py problem

### ISSUE THREAD

**Issue by peng913** [cuthalionn/Prompter#2]
Dear Author: I am getting an error running sgd_eval.sh while evaluating the SGD dataset that the model is in, I would like to get your help!
Traceback (most recent call last): File "/root/DualLoRA-main/SGD_eval_script.py", line 26, in <module> import tensorflow.compat.v1 as tf File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/__init__.py", line 49, in <module> from tensorflow._api.v2 import __internal__ File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 8, in <module> from tensorflow._api.v2.__internal__ import autograph File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py", line 8, in <module> from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34 File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/python/autograph/core/ag_ctx.py", line 21, in <module> from tensorflow.python.autograph.utils import ag_logging File "/root/miniconda3/envs/duallora/lib/python3.9/site-packages/tensorflow/pyth

**Comment by cuthalionn** [comment]
Hi, thanks for the question. 

From the error message it seems like you are running the script for another project and face some dependency issues. I am not sure I can help with this since I am not familiar with their dependencies. If you cannot run the evaluation script within the scope of this project, can you share the error message for that? I can try to help with that.
